2023-05-23 22:04:00,333 INFO: Microblog startup [in /Users/kyle/projects/tester/app/__init__.py:74]
2023-05-23 22:04:30,280 INFO: Microblog startup [in /Users/kyle/projects/tester/app/__init__.py:74]
2023-05-23 22:05:37,984 INFO: Microblog startup [in /Users/kyle/projects/tester/app/__init__.py:74]
2023-05-23 22:20:11,005 INFO: Microblog startup [in /Users/kyle/projects/tester/app/__init__.py:74]
2023-05-24 14:52:38,657 INFO: Microblog startup [in /Users/kyle/projects/tester/app/__init__.py:74]
2023-05-24 18:59:54,022 INFO: Microblog startup [in /Users/kyle/projects/tester/app/__init__.py:78]
2023-05-24 20:46:53,653 INFO: Microblog startup [in /Users/kyle/projects/tester/app/__init__.py:78]
2023-05-24 20:50:50,389 INFO: Microblog startup [in /Users/kyle/projects/tester/app/__init__.py:78]
2023-05-24 21:03:17,633 INFO: Microblog startup [in /Users/kyle/projects/tester/app/__init__.py:78]
2023-05-24 21:59:24,476 INFO: Microblog startup [in /Users/kyle/projects/tester/app/__init__.py:78]
2023-05-24 21:59:55,011 INFO: Microblog startup [in /Users/kyle/projects/tester/app/__init__.py:78]
2023-05-24 22:00:29,281 ERROR: Exception on /search [GET] [in /Users/kyle/.pyenv/versions/microblog/lib/python3.10/site-packages/flask/app.py:1744]
Traceback (most recent call last):
  File "/Users/kyle/.pyenv/versions/microblog/lib/python3.10/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/kyle/.pyenv/versions/microblog/lib/python3.10/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/kyle/.pyenv/versions/microblog/lib/python3.10/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/kyle/.pyenv/versions/microblog/lib/python3.10/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/kyle/.pyenv/versions/microblog/lib/python3.10/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/Users/kyle/projects/tester/app/main/routes.py", line 161, in search
    return render_template('search.html', title=_('Search'), posts=posts,
  File "/Users/kyle/.pyenv/versions/microblog/lib/python3.10/site-packages/flask/templating.py", line 146, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "/Users/kyle/.pyenv/versions/microblog/lib/python3.10/site-packages/jinja2/environment.py", line 1068, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/Users/kyle/.pyenv/versions/microblog/lib/python3.10/site-packages/jinja2/environment.py", line 997, in get_template
    return self._load_template(name, globals)
  File "/Users/kyle/.pyenv/versions/microblog/lib/python3.10/site-packages/jinja2/environment.py", line 958, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/Users/kyle/.pyenv/versions/microblog/lib/python3.10/site-packages/jinja2/loaders.py", line 125, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/Users/kyle/.pyenv/versions/microblog/lib/python3.10/site-packages/flask/templating.py", line 62, in get_source
    return self._get_source_fast(environment, template)
  File "/Users/kyle/.pyenv/versions/microblog/lib/python3.10/site-packages/flask/templating.py", line 98, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: search.html
2023-05-24 22:00:51,862 ERROR: Exception on /search [GET] [in /Users/kyle/.pyenv/versions/microblog/lib/python3.10/site-packages/flask/app.py:1744]
Traceback (most recent call last):
  File "/Users/kyle/.pyenv/versions/microblog/lib/python3.10/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/kyle/.pyenv/versions/microblog/lib/python3.10/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/kyle/.pyenv/versions/microblog/lib/python3.10/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/kyle/.pyenv/versions/microblog/lib/python3.10/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/kyle/.pyenv/versions/microblog/lib/python3.10/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/Users/kyle/projects/tester/app/main/routes.py", line 161, in search
    return render_template('search.html', title=_('Search'), posts=posts,
  File "/Users/kyle/.pyenv/versions/microblog/lib/python3.10/site-packages/flask/templating.py", line 146, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "/Users/kyle/.pyenv/versions/microblog/lib/python3.10/site-packages/jinja2/environment.py", line 1068, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/Users/kyle/.pyenv/versions/microblog/lib/python3.10/site-packages/jinja2/environment.py", line 997, in get_template
    return self._load_template(name, globals)
  File "/Users/kyle/.pyenv/versions/microblog/lib/python3.10/site-packages/jinja2/environment.py", line 958, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/Users/kyle/.pyenv/versions/microblog/lib/python3.10/site-packages/jinja2/loaders.py", line 125, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/Users/kyle/.pyenv/versions/microblog/lib/python3.10/site-packages/flask/templating.py", line 62, in get_source
    return self._get_source_fast(environment, template)
  File "/Users/kyle/.pyenv/versions/microblog/lib/python3.10/site-packages/flask/templating.py", line 98, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: search.html
2023-05-24 22:01:33,988 INFO: Microblog startup [in /Users/kyle/projects/tester/app/__init__.py:78]
2023-05-24 22:01:44,529 ERROR: Exception on /search [GET] [in /Users/kyle/.pyenv/versions/microblog/lib/python3.10/site-packages/flask/app.py:1744]
Traceback (most recent call last):
  File "/Users/kyle/.pyenv/versions/microblog/lib/python3.10/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/kyle/.pyenv/versions/microblog/lib/python3.10/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/kyle/.pyenv/versions/microblog/lib/python3.10/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/kyle/.pyenv/versions/microblog/lib/python3.10/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/kyle/.pyenv/versions/microblog/lib/python3.10/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/Users/kyle/projects/tester/app/main/routes.py", line 161, in search
    return render_template('search.html', title=_('Search'), posts=posts,
  File "/Users/kyle/.pyenv/versions/microblog/lib/python3.10/site-packages/flask/templating.py", line 146, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "/Users/kyle/.pyenv/versions/microblog/lib/python3.10/site-packages/jinja2/environment.py", line 1068, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/Users/kyle/.pyenv/versions/microblog/lib/python3.10/site-packages/jinja2/environment.py", line 997, in get_template
    return self._load_template(name, globals)
  File "/Users/kyle/.pyenv/versions/microblog/lib/python3.10/site-packages/jinja2/environment.py", line 958, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/Users/kyle/.pyenv/versions/microblog/lib/python3.10/site-packages/jinja2/loaders.py", line 125, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/Users/kyle/.pyenv/versions/microblog/lib/python3.10/site-packages/flask/templating.py", line 62, in get_source
    return self._get_source_fast(environment, template)
  File "/Users/kyle/.pyenv/versions/microblog/lib/python3.10/site-packages/flask/templating.py", line 98, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: search.html
2023-05-24 22:04:55,834 INFO: Microblog startup [in /Users/kyle/projects/tester/app/__init__.py:78]
2023-05-24 22:06:00,244 INFO: Microblog startup [in /Users/kyle/projects/tester/app/__init__.py:78]
